{{- if and
  (eq "keycloak" .Values.auth.kind)
  .Values.auth.keycloak.secret.enabled
  .Values.auth.keycloak.secret.external.enabled
}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-keycloak-client-external-secret
spec:
  refreshInterval: {{ .Values.auth.keycloak.secret.external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.keycloak.secret.external.store.name | quote }}
    kind: {{ .Values.auth.keycloak.secret.external.store.kind }}
  target:
    name: {{ .Values.auth.keycloak.secret.name }}
  data:
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.auth.keycloak.secret.external.store.path | quote }}
        property: {{ .Values.auth.keycloak.secret.external.store.key | quote }}
{{- end }}
