{{- if and
  .Values.auth.keycloak.enabled
  .Values.auth.keycloak.settings.enabled
  .Values.auth.keycloak.settings.admin.secret.enabled
  .Values.auth.keycloak.settings.admin.secret.external.enabled
 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-keycloak-admin-external-secret
spec:
  refreshInterval: {{ .Values.auth.keycloak.settings.admin.secret.external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.keycloak.settings.admin.secret.external.store.name | quote }}
    kind: {{ .Values.auth.keycloak.settings.admin.secret.external.store.kind }}
  target:
    name: {{ .Values.auth.keycloak.settings.admin.secret.name }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.auth.keycloak.settings.admin.secret.external.store.path | quote }}
        property: {{ .Values.auth.keycloak.settings.admin.secret.external.store.usernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.auth.keycloak.settings.admin.secret.external.store.path | quote }}
        property: {{ .Values.auth.keycloak.settings.admin.secret.external.store.passwordKey }}
{{- end }}
