{{- if and
    (eq "keycloak" .Values.auth.kind)
    .Values.auth.keycloak.persistence.connection.secret.enabled
    .Values.auth.keycloak.persistence.connection.secret.externalSecret.enabled
    (not .Values.auth.keycloak.external.enabled)
}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-keycloak-postgres-external-secret
spec:
  refreshInterval: {{ .Values.auth.keycloak.persistence.connection.secret.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.keycloak.persistence.connection.secret.externalSecret.store.name | quote }}
    kind: {{ .Values.auth.keycloak.persistence.connection.secret.externalSecret.store.kind }}
  target:
    name: {{ .Values.auth.keycloak.persistence.connection.secret.name }}
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.auth.keycloak.persistence.connection.secret.externalSecret.store.path | quote }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.auth.keycloak.persistence.connection.secret.externalSecret.store.path | quote }}
        property: password
{{- end }}
