{{- if and (eq "keycloak" .Values.auth.kind) .Values.auth.keycloak.ldap.enabled .Values.auth.keycloak.ldap.testing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ontrack.fullname" . }}-ldap
  labels:
    {{- include "ontrack.labels.ldap" . | nindent 4 }}
spec:
  replicas: {{ .Values.ontrack.ui.replicas }}
  selector:
    matchLabels:
      {{- include "ontrack.selectorLabels.ldap" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontrack.selectorLabels.ldap" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ontrack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
      {{- end }}
        - name: {{ .Chart.Name }}-ldap
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.auth.keycloak.ldap.testing.image }}:{{ .Values.auth.keycloak.ldap.testing.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --loglevel
            - debug
            {{- if .Values.auth.keycloak.ldap.testing.provisioning.enabled }}
            - --copy-service
            {{- end }}
          {{- if .Values.auth.keycloak.ldap.testing.provisioning.enabled }}
          volumeMounts:
            - mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom/admin.ldif
              name: {{ include "ontrack.fullname" . }}-ldap-bootstrap
              subPath: admin.ldif
          {{- end }}
          env:
            {{- if .Values.auth.keycloak.ldap.testing.provisioning.enabled }}
            - name: LDAP_ORGANISATION
              value: {{ .Values.auth.keycloak.ldap.testing.provisioning.organisation | quote }}
            - name: LDAP_DOMAIN
              value: "{{ .Values.auth.keycloak.ldap.testing.provisioning.domain.name }}.{{ .Values.auth.keycloak.ldap.testing.provisioning.domain.extension }}"
            {{- end }}
            - name: LDAP_ADMIN_PASSWORD
              value: {{ .Values.auth.keycloak.ldap.testing.admin.password | quote }}
            - name: LDAP_LOG_LEVEL
              value: "256"
          ports:
            - name: ldap
              containerPort: 389
              protocol: TCP
            - name: ldaps
              containerPort: 636
              protocol: TCP
          resources: {{ toYaml .Values.auth.keycloak.ldap.testing.resources | nindent 12 }}
      {{- if .Values.auth.keycloak.ldap.testing.provisioning.enabled }}
      volumes:
        - name: {{ include "ontrack.fullname" . }}-ldap-bootstrap
          configMap:
            name: {{ include "ontrack.fullname" . }}-ldap-bootstrap
            optional: false
            items:
              - key: admin.ldif
                path: admin.ldif
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}