{{- if and (eq "oidc" .Values.auth.kind) .Values.auth.oidc.credentials.secret.enabled .Values.auth.oidc.credentials.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-oidc-external-secret
spec:
  refreshInterval: {{ .Values.auth.oidc.credentials.secret.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.auth.oidc.credentials.secret.externalSecret.store.name | quote }}
    kind: {{ .Values.auth.oidc.credentials.secret.externalSecret.store.kind }}
  target:
    name: {{ .Values.auth.oidc.credentials.secret.secretName }}
  data:
    - secretKey: clientId
      remoteRef:
        key: {{ .Values.auth.oidc.credentials.secret.externalSecret.store.path | quote }}
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: {{ .Values.auth.oidc.credentials.secret.externalSecret.store.path | quote }}
        property: clientSecret
{{- end }}
