apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ontrack.fullname" . }}
  labels:
    {{- include "ontrack.labels" . | nindent 4 }}
spec:
  serviceName: ontrack
  selector:
    matchLabels:
      {{- include "ontrack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontrack.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.elasticsearch.enabled }}
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox:1.36
          command:
            - 'sh'
            - '-c'
            - |
              until nc -z {{ .Release.Name }}-elasticsearch 9200; do
                echo "Waiting for Elasticsearch to be ready..."
                sleep 5
              done
              echo "Elasticsearch is ready!"
      {{- end }}
      serviceAccountName: {{ include "ontrack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
      {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: ontrack
              mountPath: /var/ontrack/data
            {{- if .Values.ontrack.casc.enabled }}
            {{- if .Values.ontrack.casc.map }}
            - name: casc
              mountPath: "{{ .Values.ontrack.casc.directory }}/map"
            {{- end }}
            {{- if .Values.ontrack.casc.secret }}
            - name: casc-secret
              mountPath: "{{ .Values.ontrack.casc.directory }}/secret"
            {{- end }}
            {{- if .Values.casc }}
            - name: casc-values
              mountPath: "{{ .Values.ontrack.casc.directory }}/values"
            {{- end }}
            {{- end }}
            {{- if eq .Values.ontrack.config.key_store "secret" }}
            - name: ontrack-key-store
              mountPath: {{ .Values.ontrack.config.secret_key_store.directory | quote }}
              readOnly: true
            {{- end }}
            {{- range $secret := .Values.ontrack.casc.secrets.names }}
            - name: {{ $secret | quote }}
              mountPath: "{{ $.Values.ontrack.casc.secrets.directory }}/{{ $secret }}"
              readOnly: true
            {{- end }}
            {{- if .Values.ontrack.application_yaml }}
            - name: application-yaml
              mountPath: /var/ontrack/config
              readOnly: true
            {{- end }}
          env:
            ########################################
            # General configuration
            ########################################
            - name: ONTRACK_CONFIG_URL
              value: {{ .Values.ontrack.url | quote }}
            - name: PROFILE
              value: {{ .Values.ontrack.profiles | quote }}
            ########################################
            # Application properties
            ########################################
            {{- if .Values.ontrack.application_yaml }}
            - name: ONTRACK_ARGS
              value: "--spring.config.location=classpath:/config/application.yml,/var/ontrack/config/application.yaml"
            {{- else }}
            - name: ONTRACK_ARGS
              value: ""
            {{- end }}
            ########################################
            # Database configuration
            ########################################
            {{- if .Values.postgresql.local }}
            # For test service
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-postgresql-hl:5432/{{ .Values.postgresql.auth.database }}"
            # For a managed database, using external environment variables
            {{- else if .Values.postgresql.postgresFromEnv }}
            # Nothing to be declared here
            {{- else }}
            # For a managed database, using the URL
            - name: SPRING_DATASOURCE_URL
              value: {{ required "When local Postgres service is disabled, the postgresql.postgresqlUrl value must be set" .Values.postgresql.postgresqlUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            {{- end }}
            ########################################
            # Key management
            ########################################
            - name: ONTRACK_CONFIG_KEY_STORE
              value: {{ .Values.ontrack.config.key_store | quote }}
            {{- if eq .Values.ontrack.config.key_store "secret" }}
            - name: ONTRACK_CONFIG_FILE_KEY_STORE_DIRECTORY
              value: {{ .Values.ontrack.config.secret_key_store.directory | quote }}
            {{- end }}
            ########################################
            # Elasticsearch configuration
            ########################################
            - name: SPRING_ELASTICSEARCH_URIS
              value: "http://{{ .Release.Name }}-elasticsearch-master-hl:9200"
            ########################################
            # RabbitMQ configuration
            ########################################
            - name: SPRING_RABBITMQ_HOST
              value: "{{ .Release.Name }}-rabbitmq-headless"
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: SPRING_RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.auth.password | quote }}
            ########################################
            # Authentication
            ########################################
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_PROVISIONING
              value: {{ .Values.auth.provisioning | quote }}
            {{- if .Values.auth.provisioning }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_ADMIN_EMAIL
              value: {{ .Values.auth.admin.email | quote }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_ADMIN_FULLNAME
              value: {{ .Values.auth.admin.fullName | quote }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_ADMIN_GROUPNAME
              value: {{ .Values.auth.admin.groupName | quote }}
            {{- end }}
            {{- if .Values.auth.oidc.enabled }}
              {{- if .Values.auth.oidc.trailingSlash }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "{{ .Values.auth.oidc.issuer }}/"
              {{- else }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "{{ .Values.auth.oidc.issuer }}"
              {{- end }}
            {{- end }}
            {{- if .Values.auth.keycloak.enabled }}
            {{- if .Values.auth.keycloak.external.enabled }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.auth.keycloak.external.url | quote }}
            {{- else }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.ontrack.url }}/{{ .Values.auth.keycloak.service.path }}/realms/{{ .Values.auth.keycloak.realm }}
            {{- end }}
            {{- end }}
            # JWT specifics
            {{- if .Values.auth.jwt }}
              {{- if .Values.auth.jwt.debug }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_JWT_DEBUG
              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: DEBUG
              {{- end }}
              {{- if .Values.auth.jwt.audience }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_AUDIENCES
              value: {{ .Values.auth.jwt.audience | quote }}
              {{- end }}
              {{- if .Values.auth.jwt.typ }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_JWT_TYP
              value: {{ .Values.auth.jwt.typ | quote }}
              {{- end }}
              {{- if .Values.auth.jwt.claims }}
                {{- if .Values.auth.jwt.claims.email }}
            - name: ONTRACK_CONFIG_SECURITY_AUTHORIZATION_JWT_CLAIMS_EMAIL
              value: {{ .Values.auth.jwt.claims.email | quote }}
                {{- end }}
              {{- end }}
            {{- end }}
            ########################################
            # Metrics tags
            ########################################
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: {{ .Values.ontrack.management.metrics.tags.application | quote }}
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION_INSTANCE
              value: {{ .Values.ontrack.management.metrics.tags.application_instance | quote }}
            ########################################
            # Casc
            ########################################
            {{- if .Values.ontrack.casc.enabled }}
            - name: ONTRACK_CONFIG_CASC_ENABLED
              value: "true"
            {{- $locations := list -}}
            {{- if .Values.ontrack.casc.map -}}
              {{- $locations = append $locations (printf "file://%s/map" .Values.ontrack.casc.directory) -}}
            {{- end -}}
            {{- if .Values.ontrack.casc.secret -}}
              {{- $locations = append $locations (printf "file://%s/secret" .Values.ontrack.casc.directory) -}}
            {{- end -}}
            {{- if .Values.casc -}}
              {{- $locations = append $locations (printf "file://%s/values" .Values.ontrack.casc.directory) -}}
            {{- end -}}
            {{- $locationsValue := join "," $locations }}
            - name: ONTRACK_CONFIG_CASC_LOCATIONS
              value: {{ $locationsValue | quote }}
            {{- if .Values.ontrack.casc.reloading.enabled }}
            - name: ONTRACK_CONFIG_CASC_RELOADING_ENABLED
              value: "true"
            - name: ONTRACK_CONFIG_CASC_RELOADING_CRON
              value: {{ .Values.ontrack.casc.reloading.cron | quote }}
            {{- end }}
            - name: ONTRACK_CONFIG_CASC_UPLOAD_ENABLED
              value: {{ .Values.ontrack.casc.upload.enabled | quote }}
            {{- end }}
            - name: ONTRACK_CONFIG_CASC_SECRETS_TYPE
              value: {{ .Values.ontrack.casc.secrets.mapping | quote }}
            - name: ONTRACK_CONFIG_CASC_SECRETS_DIRECTORY
              value: {{ .Values.ontrack.casc.secrets.directory | quote }}
            ########################################
            # License management
            ########################################
            - name: ONTRACK_CONFIG_LICENSE_KEY
              value: {{ .Values.ontrack.config.license.key | quote }}
            ########################################
            # Arbitrary environment variables
            ########################################
            {{- with .Values.ontrack.env }}
            {{- . | toYaml | trim | nindent 12 }}
            {{- end }}
          envFrom:
          {{- range .Values.ontrack.extraConfig.secrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.ontrack.extraConfig.configmaps }}
            - configMapRef:
                name: {{ . }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: mgt
              containerPort: 8800
              protocol: TCP
          resources: {{ toYaml .Values.ontrack.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /manage/health/readiness
              port: mgt
            failureThreshold: 3
            periodSeconds: 60
            initialDelaySeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: ontrack
          {{- if .Values.ontrack.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ontrack.fullname" . }}
          {{- else }}
          emptyDir: {{- toYaml .Values.emptyDir | nindent 12 }}
          {{- end  }}
        {{- if eq .Values.ontrack.config.key_store "secret" }}
        - name: ontrack-key-store
          secret:
            secretName: {{ .Values.ontrack.config.secret_key_store.secret_name | quote }}
            optional: false
        {{- end }}
        {{- if and .Values.ontrack.casc.enabled .Values.ontrack.casc.map }}
        - name: casc
          configMap:
            name: {{ .Values.ontrack.casc.map | quote }}
            optional: false
        {{- end }}
        {{- if and .Values.ontrack.casc.enabled .Values.ontrack.casc.secret }}
        - name: casc-secret
          secret:
            secretName: {{ .Values.ontrack.casc.secret | quote }}
            optional: false
        {{- end }}
        {{- if and .Values.ontrack.casc.enabled .Values.casc }}
        - name: casc-values
          configMap:
            name: {{ include "ontrack.fullname" . }}-casc
            optional: false
        {{- end }}
        {{- range .Values.ontrack.casc.secrets.names }}
        - name: {{ . | quote }}
          secret:
            secretName: {{ . | quote }}
            optional: false
        {{- end }}
        {{- if .Values.ontrack.application_yaml }}
        - name: application-yaml
          configMap:
            name: {{ include "ontrack.fullname" . }}-application
            optional: false
        {{- end }}
