{{- if and .Values.ontrack.casc.enabled .Values.casc .Values.ontrack.casc.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-casc-secrets
spec:
  data:
    {{- range $secret := .Values.ontrack.casc.externalSecrets.secretKeys }}
    - remoteRef:
        key: {{ $secret.path }}
        property: {{ $secret.sourceKey }}
      secretKey: {{ $secret.targetKey }}
    {{- end }}
  refreshInterval: {{ .Values.ontrack.casc.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.ontrack.casc.externalSecrets.store.kind }}
    name: {{ .Values.ontrack.casc.externalSecrets.store.name }}
  target:
    name: {{ .Values.ontrack.casc.externalSecrets.secretName }}
{{- end -}}