{{- if and (eq .Values.ontrack.config.key_store "secret") .Values.ontrack.config.secret_key_store.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-ontrack-encryption-key
spec:
  refreshInterval: {{ .Values.ontrack.config.secret_key_store.external.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.ontrack.config.secret_key_store.external.store.name | quote }}
    kind: {{ .Values.ontrack.config.secret_key_store.external.store.kind }}
  target:
    name: {{ .Values.ontrack.config.secret_key_store.secret_name }}
  data:
    - secretKey: net.nemerosa.ontrack.security.EncryptionServiceImpl.encryption
      remoteRef:
        key: {{ .Values.ontrack.config.secret_key_store.external.store.path | quote }}
        property: {{ .Values.ontrack.config.secret_key_store.external.store.key | quote }}
        decodingStrategy: Base64
{{- end }}
